var h,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={jb:!0},ea={};try{ea.__proto__=da;ca=ea.jb;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var fa=ba,k=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ja=b.prototype},ha="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},l="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:
this,ia=function(){ia=function(){};l.Symbol||(l.Symbol=ja)},ja=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),n=function(){ia();var a=l.Symbol.iterator;a||(a=l.Symbol.iterator=l.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ha(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ka(this)}});n=function(){}},ka=function(a){var b=0;return la(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},la=function(a){n();a={next:a};a[l.Symbol.iterator]=
function(){return this};return a},ma=function(a){n();var b=a[Symbol.iterator];return b?b.call(a):ka(a)},p=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},na=function(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ha(c,a,{configurable:!0,writable:!0,value:b})}};
na("WeakMap",function(a){function b(a){p(a,d)||ha(a,d,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(t){return!1}}())return a;var d="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var e=0,f=function(a){this.fa=(e+=Math.random()+
1).toString();if(a){ia();n();a=ma(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,c){b(a);if(!p(a,d))throw Error("WeakMap key fail: "+a);a[d][this.fa]=c;return this};f.prototype.get=function(a){return p(a,d)?a[d][this.fa]:void 0};f.prototype.has=function(a){return p(a,d)&&p(a[d],this.fa)};f.prototype.delete=function(a){return p(a,d)&&p(a[d],this.fa)?delete a[d][this.fa]:!1};return f});
na("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(ma([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(bd){return!1}}())return a;ia();n();var b=new WeakMap,c=function(a){this.da=
{};this.m=f();this.size=0;if(a){a=ma(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.da[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.m,previous:this.m.previous,head:this.m,key:a,value:b},c.list.push(c.entry),this.m.previous.next=c.entry,this.m.previous=c.entry,this.size++);return this};c.prototype.delete=function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.da[a.id],
a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.da={};this.m=this.m.previous=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).entry};c.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,
function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++g,b.set(c,d)):d="p_"+c;var e=a.da[d];if(e&&p(a.da,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},e=function(a,
b){var c=a.m;return la(function(){if(c){for(;c.head!=a.m;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.previous=a.next=a.head=a},g=0;return c});
na("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(ma([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;ia();n();var b=function(a){this.c=new Map;
if(a){a=ma(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.c.size};b.prototype.add=function(a){a=0===a?0:a;this.c.set(a,a);this.size=this.c.size;return this};b.prototype.delete=function(a){a=this.c.delete(a);this.size=this.c.size;return a};b.prototype.clear=function(){this.c.clear();this.size=0};b.prototype.has=function(a){return this.c.has(a)};b.prototype.entries=function(){return this.c.entries()};b.prototype.values=function(){return this.c.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.c.forEach(function(d){return a.call(b,d,d,c)})};return b});
na("String.prototype.endsWith",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.endsWith must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.endsWith must not be a regular expression");var b=this+"";a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var e=a.length;0<e&&0<c;)if(b[--c]!=a[--e])return!1;return 0>=e}});window.Tb=!0;var q=this,r=function(a){return"string"==typeof a},u=function(){},v=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=
typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},oa=function(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length},w=function(a){return"function"==v(a)},pa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},qa=function(a,b,c){return a.call.apply(a.bind,arguments)},ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,
2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},sa=function(a,b,c){sa=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return sa.apply(null,arguments)},ta=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},ua=Date.now||function(){return+new Date},
va=function(a,b){function c(){}c.prototype=b.prototype;a.Ja=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ub=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var wa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var xa=function(a,b){if(a!==b)throw Error("Expected |type| == "+a+" but got: "+b);},ya=function(a,b){if(r(a))return a;throw Error("Expected string for |"+b+"| but got "+v(a)+": "+a);};var x=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};va(x,Error);x.prototype.name="CustomError";var za=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");x.call(this,c+a[d])};va(za,x);za.prototype.name="AssertionError";
var Aa=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new za(""+e,f||[]);},y=function(a,b,c){a||Aa("",null,b,Array.prototype.slice.call(arguments,2))},Ba=function(a,b){throw new za("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},Ca=function(a,b,c){"number"==typeof a||Aa("Expected number but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2));return a},Da=function(a,b,c){w(a)||Aa("Expected function but got %s: %s.",[v(a),
a],b,Array.prototype.slice.call(arguments,2))};var Ea=function(){this.Na=new Set;this.ta=new Map;this.ia=new Map};Ea.prototype.add=function(a,b,c){b=void 0===b?"":b;c=void 0===c?null:c;y(null==c||""!=b);if(""==b)this.Na.add(a);else if(c){var d=this.ia.get(b);d||(d=new Map,this.ia.set(b,d));d.set(a,c)}else c=this.ta.get(b),c||(c=new Set,this.ta.set(b,c)),c.add(a)};
Ea.prototype.filter=function(a){var b={},c;for(c in a)b[c]=a[c];a=a.type;for(var d in b)this.Na.has(d)||null!=b[d]&&(a&&this.ta.has(a)&&this.ta.get(a).has(d)||(a&&this.ia.has(a)&&this.ia.get(a).has(d)&&"object"==typeof b[d]?b[d]=this.ia.get(a).get(d).filter(b[d]):b[d]="<redacted>"));return b};var z=new Ea;z.add("id");z.add("type");var Fa=function(a,b){if(!a)throw Error("object == null");ya(a.type,"type");"any"!=b&&xa(a.type,b);return{type:a.type}};z.add("version","hello");var Ga=function(a){var b=Fa.call(this,a,"setClipboard");b.payload=ya(a.payload,"payload");return b},Ha=function(a){var b={type:a.type};b.payload=a.payload;return b},A=function(a,b,c){var d=Error.call(this,a+" returns error code: "+b+" details: "+c);this.message=d.message;"stack"in d&&(this.stack=d.stack);this.lb=a;this.errorCode=b;this.pb=c};k(A,Error);
A.prototype.h=function(){return{type:"error",api:this.lb,errorCode:this.errorCode,details:this.pb,stack:this.stack}};var Ia=function(a){var b=ya(chrome.runtime.lastError.message,"unknown");return new A(a,"CHROME_RUNTIME",b)},B=function(a,b){return b instanceof A?b:new A(a,"UNEXPECTED_ERROR",String(b))};z.add("api","error");z.add("errorCode","error");z.add("details","error");z.add("stack","error");var Ja=function(a){return{h:function(){return{type:a}}}},Ka=Ja("tabs.highlightResponse");var D=function(){this.Y=this.Y;this.T=this.T};D.prototype.Y=!1;D.prototype.isDisposed=function(){return this.Y};D.prototype.Oa=function(){this.Y||(this.Y=!0,this.J())};var La=function(a,b){a.Y?b():(a.T||(a.T=[]),a.T.push(b))};D.prototype.J=function(){if(this.T)for(;this.T.length;)this.T.shift()()};var Ma=function(a){a&&"function"==typeof a.Oa&&a.Oa()};var Na=Array.prototype.indexOf?function(a,b){y(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(r(a))return r(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Oa=Array.prototype.forEach?function(a,b,c){y(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Pa=function(a){return Array.prototype.concat.apply([],arguments)},
Qa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ra=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},E=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},Sa=function(a,b){return a<b?-1:a>b?1:0};var F;a:{var Ta=q.navigator;if(Ta){var Ua=Ta.userAgent;if(Ua){F=Ua;break a}}F=""}var G=function(a){return-1!=F.indexOf(a)};var Va=function(a){Va[" "](a);return a};Va[" "]=u;var Wa=G("Opera"),Xa=G("Trident")||G("MSIE"),Ya=G("Edge"),Za=G("Gecko")&&!(-1!=F.toLowerCase().indexOf("webkit")&&!G("Edge"))&&!(G("Trident")||G("MSIE"))&&!G("Edge"),$a=-1!=F.toLowerCase().indexOf("webkit")&&!G("Edge"),ab=function(){var a=q.document;return a?a.documentMode:void 0},bb;
a:{var cb="",db=function(){var a=F;if(Za)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ya)return/Edge\/([\d\.]+)/.exec(a);if(Xa)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if($a)return/WebKit\/(\S+)/.exec(a);if(Wa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();db&&(cb=db?db[1]:"");if(Xa){var eb=ab();if(null!=eb&&eb>parseFloat(cb)){bb=String(eb);break a}}bb=cb}var fb=bb,gb={},hb;var ib=q.document;hb=ib&&Xa?ab()||("CSS1Compat"==ib.compatMode?parseInt(fb,10):5):void 0;var jb=Object.freeze||function(a){return a};var kb=function(a,b,c){this.reset(a,b,c,void 0,void 0)};kb.prototype.za=null;var lb=0;kb.prototype.reset=function(a,b,c,d,e){"number"==typeof e||lb++;this.gb=d||ua();this.R=a;this.wb=b;this.Ra=c;delete this.za};kb.prototype.cb=function(a){this.R=a};kb.prototype.getMessage=function(){return this.wb};var H=function(a){this.ha=a;this.ea=this.ya=this.R=this.C=null},I=function(a,b){this.name=a;this.value=b};I.prototype.toString=function(){return this.name};var mb=new I("SHOUT",1200),J=new I("SEVERE",1E3),nb=new I("WARNING",900),ob=new I("INFO",800),pb=new I("CONFIG",700);H.prototype.getName=function(){return this.ha};H.prototype.getParent=function(){return this.C};H.prototype.getChildren=function(){this.ya||(this.ya={});return this.ya};H.prototype.cb=function(a){this.R=a};
var qb=function(a){if(a.R)return a.R;if(a.C)return qb(a.C);Ba("Root logger has no level set.");return null};H.prototype.log=function(a,b,c){if(a.value>=qb(this).value)for(w(b)&&(b=b()),a=new kb(a,String(b),this.ha),c&&(a.za=c),c=this;c;){var d=c,e=a;if(d.ea)for(var f=0;b=d.ea[f];f++)b(e);c=c.getParent()}};H.prototype.info=function(a,b){this.log(ob,a,b)};H.prototype.config=function(a,b){this.log(pb,a,b)};
var rb={},sb=null,tb=function(){sb||(sb=new H(""),rb[""]=sb,sb.cb(pb))},K=function(a){tb();var b;if(!(b=rb[a])){b=new H(a);var c=a.lastIndexOf("."),d=a.substr(c+1);c=K(a.substr(0,c));c.getChildren()[d]=b;b.C=c;rb[a]=b}return b};var ub=function(a){var b=L;b&&b.log(nb,a,void 0)},M=function(a,b){a&&a.info(b,void 0)};var vb="StopIteration"in q?q.StopIteration:{message:"StopIteration",stack:""},wb=function(){};wb.prototype.next=function(){throw vb;};wb.prototype.ib=function(){return this};var xb=function(a,b){this.c={};this.j=[];this.la=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};h=xb.prototype;h.G=function(){yb(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.c[this.j[b]]);return a};h.M=function(){yb(this);return this.j.concat()};h.ca=function(a){return N(this.c,a)};h.clear=function(){this.c={};this.la=this.g=this.j.length=0};
h.remove=function(a){return N(this.c,a)?(delete this.c[a],this.g--,this.la++,this.j.length>2*this.g&&yb(this),!0):!1};var yb=function(a){if(a.g!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];N(a.c,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.g!=a.j.length){var e={};for(c=b=0;b<a.j.length;)d=a.j[b],N(e,d)||(a.j[c++]=d,e[d]=1),b++;a.j.length=c}};h=xb.prototype;h.get=function(a,b){return N(this.c,a)?this.c[a]:b};h.set=function(a,b){N(this.c,a)||(this.g++,this.j.push(a),this.la++);this.c[a]=b};
h.addAll=function(a){if(a instanceof xb)for(var b=a.M(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new xb(this)};h.ib=function(a){yb(this);var b=0,c=this.la,d=this,e=new wb;e.next=function(){if(c!=d.la)throw Error("The map has changed since the iterator was created");if(b>=d.j.length)throw vb;var e=d.j[b++];return a?e:d.c[e]};return e};
var N=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var zb=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(r(a))return a.split("");if(oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},Ab=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(oa(a)||r(a))Oa(a,b,c);else{if(a.M&&"function"==typeof a.M)var d=a.M();else if(a.G&&"function"==typeof a.G)d=void 0;else if(oa(a)||r(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;
e=zb(a);f=e.length;for(var g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var Bb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Cb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var O=function(a){this.D=this.V=this.N="";this.w=null;this.P=this.H="";this.B=this.ub=!1;if(a instanceof O){this.B=a.B;Db(this,a.N);var b=a.V;P(this);this.V=b;b=a.D;P(this);this.D=b;Eb(this,a.w);b=a.H;P(this);this.H=b;Fb(this,a.F.clone());a=a.P;P(this);this.P=a}else a&&(b=String(a).match(Bb))?(this.B=!1,Db(this,b[1]||"",!0),a=b[2]||"",P(this),this.V=Gb(a),a=b[3]||"",P(this),this.D=Gb(a,!0),Eb(this,b[4]),a=b[5]||"",P(this),this.H=Gb(a,!0),Fb(this,b[6]||"",!0),a=b[7]||"",P(this),this.P=Gb(a)):(this.B=
!1,this.F=new Q(null,this.B))};O.prototype.toString=function(){var a=[],b=this.N;b&&a.push(Hb(b,Ib,!0),":");var c=this.D;if(c||"file"==b)a.push("//"),(b=this.V)&&a.push(Hb(b,Ib,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.w,null!=c&&a.push(":",String(c));if(c=this.H)this.D&&"/"!=c.charAt(0)&&a.push("/"),a.push(Hb(c,"/"==c.charAt(0)?Jb:Kb,!0));(c=this.F.toString())&&a.push("?",c);(c=this.P)&&a.push("#",Hb(c,Lb));return a.join("")};
O.prototype.resolve=function(a){var b=this.clone(),c=!!a.N;c?Db(b,a.N):c=!!a.V;if(c){var d=a.V;P(b);b.V=d}else c=!!a.D;c?(d=a.D,P(b),b.D=d):c=null!=a.w;d=a.H;if(c)Eb(b,a.w);else if(c=!!a.H){if("/"!=d.charAt(0))if(this.D&&!this.H)d="/"+d;else{var e=b.H.lastIndexOf("/");-1!=e&&(d=b.H.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var m=e[g++];"."==m?d&&g==e.length&&f.push(""):".."==
m?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(m),d=!0)}d=f.join("/")}else d=e}c?(P(b),b.H=d):c=""!==a.F.toString();c?Fb(b,a.F.clone()):c=!!a.P;c&&(a=a.P,P(b),b.P=a);return b};O.prototype.clone=function(){return new O(this)};
var Db=function(a,b,c){P(a);a.N=c?Gb(b,!0):b;a.N&&(a.N=a.N.replace(/:$/,""))},Eb=function(a,b){P(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.w=b}else a.w=null},Fb=function(a,b,c){P(a);b instanceof Q?(a.F=b,a.F.Ia(a.B)):(c||(b=Hb(b,Mb)),a.F=new Q(b,a.B))};O.prototype.getQuery=function(){return this.F.toString()};O.prototype.removeParameter=function(a){P(this);this.F.remove(a);return this};var P=function(a){if(a.ub)throw Error("Tried to modify a read-only Uri");};
O.prototype.Ia=function(a){this.B=a;this.F&&this.F.Ia(a)};
var Gb=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Hb=function(a,b,c){return r(a)?(a=encodeURI(a).replace(b,Nb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Nb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ib=/[#\/\?@]/g,Kb=/[#\?:]/g,Jb=/[#\?]/g,Mb=/[#\?@]/g,Lb=/#/g,Q=function(a,b){this.g=this.b=null;this.v=a||null;this.B=!!b},R=function(a){a.b||(a.b=new xb,a.g=0,a.v&&Cb(a.v,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};h=Q.prototype;h.add=function(a,b){R(this);this.v=null;a=S(this,a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.g=Ca(this.g)+1;return this};h.remove=function(a){R(this);a=S(this,a);return this.b.ca(a)?(this.v=null,this.g=Ca(this.g)-this.b.get(a).length,this.b.remove(a)):!1};h.clear=function(){this.b=this.v=null;this.g=0};h.ca=function(a){R(this);a=S(this,a);return this.b.ca(a)};
h.forEach=function(a,b){R(this);this.b.forEach(function(c,d){Oa(c,function(c){a.call(b,c,d,this)},this)},this)};h.M=function(){R(this);for(var a=this.b.G(),b=this.b.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.G=function(a){R(this);var b=[];if(r(a))this.ca(a)&&(b=Pa(b,this.b.get(S(this,a))));else{a=this.b.G();for(var c=0;c<a.length;c++)b=Pa(b,a[c])}return b};
h.set=function(a,b){R(this);this.v=null;a=S(this,a);this.ca(a)&&(this.g=Ca(this.g)-this.b.get(a).length);this.b.set(a,[b]);this.g=Ca(this.g)+1;return this};h.get=function(a,b){if(!a)return b;a=this.G(a);return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.v)return this.v;if(!this.b)return"";for(var a=[],b=this.b.M(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.G(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.v=a.join("&")};h.clone=function(){var a=new Q;a.v=this.v;this.b&&(a.b=this.b.clone(),a.g=this.g);return a};var S=function(a,b){b=String(b);a.B&&(b=b.toLowerCase());return b};
Q.prototype.Ia=function(a){a&&!this.B&&(R(this),this.v=null,this.b.forEach(function(a,c){var b=c.toLowerCase();c!=b&&(this.remove(c),this.remove(b),0<a.length&&(this.v=null,this.b.set(S(this,b),Qa(a)),this.g=Ca(this.g)+a.length))},this));this.B=a};Q.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Ab(arguments[b],function(a,b){this.add(b,a)},this)};var Ob=function(a,b){D.call(this);this.sa=a;this.Ta=b;this.Ga=new Map;this.Da=new Map;this.Sa=this.sb.bind(this);this.Va=this.tb.bind(this)};k(Ob,D);Ob.prototype.start=function(){this.sa.addListener(this.Va);this.Ta.addListener(this.Sa)};Ob.prototype.J=function(){this.sa.removeListener(this.Va);this.Ta.removeListener(this.Sa);D.prototype.J.call(this)};
Ob.prototype.sb=function(a){var b=new O(a.sender.url);b.D.endsWith("google.com")||(ub("Rejecting incoming connection from domain: "+b.D),a.disconnect());if(b=this.Ga.get(a.name))b.onConnect(a);else a.disconnect()};
Ob.prototype.tb=function(a,b,c){try{var d=Fa(a,"any").type;if("hello"==d)return c({type:"hello",version:chrome.runtime.getManifest().version}),!1;var e=this.Da.get(d);return e?e.onMessage(a,b,c):(ub("No handler is registered for type: "+d),!1)}catch(f){return L&&L.log(J,"Error handling message",f),!1}};
var Pb=function(a,b){var c=b.ha;a.Ga.has(c)?L&&L.log(J,"A service with name: "+c+" is already registered.",void 0):(a.Ga.set(c,b),La(a,ta(Ma,b)))},Qb=function(a,b){for(var c=b.Pa(),d=0;d<c.length;d++){var e=c[d];if(a.Da.has(e)){L&&L.log(J,"A message handler with type: "+e+" is already registered.",void 0);return}}for(d=0;d<c.length;d++)a.Da.set(c[d],b);La(a,ta(Ma,b))},L=K("extension.EventPage");var Rb;(Rb=!Xa)||(Rb=9<=Number(hb));var Sb=Rb,Tb;
if(Tb=Xa){var Ub;if(Object.prototype.hasOwnProperty.call(gb,"9"))Ub=gb["9"];else{for(var Vb=0,Wb=Ra(String(fb)).split("."),Xb=Ra("9").split("."),Yb=Math.max(Wb.length,Xb.length),Zb=0;0==Vb&&Zb<Yb;Zb++){var $b=Wb[Zb]||"",ac=Xb[Zb]||"";do{var bc=/(\d*)(\D*)(.*)/.exec($b)||["","","",""],cc=/(\d*)(\D*)(.*)/.exec(ac)||["","","",""];if(0==bc[0].length&&0==cc[0].length)break;Vb=Sa(0==bc[1].length?0:parseInt(bc[1],10),0==cc[1].length?0:parseInt(cc[1],10))||Sa(0==bc[2].length,0==cc[2].length)||Sa(bc[2],cc[2]);
$b=bc[3];ac=cc[3]}while(0==Vb)}Ub=gb["9"]=0<=Vb}Tb=!Ub}var dc=Tb,ec=function(){if(!q.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{q.addEventListener("test",u,b),q.removeEventListener("test",u,b)}catch(c){}return a}();var fc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Fa=!1};fc.prototype.stopPropagation=function(){this.Fa=!0};fc.prototype.preventDefault=function(){this.defaultPrevented=!0};var T=function(a,b){fc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.Z=null;a&&this.init(a,b)};va(T,fc);var gc=jb({2:"touch",3:"pen",4:"mouse"});
T.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(Za){a:{try{Va(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.offsetX=$a||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=$a||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,
this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=
r(a.pointerType)?a.pointerType:gc[a.pointerType]||"";this.state=a.state;this.Z=a;a.defaultPrevented&&this.preventDefault()};T.prototype.stopPropagation=function(){T.Ja.stopPropagation.call(this);this.Z.stopPropagation?this.Z.stopPropagation():this.Z.cancelBubble=!0};T.prototype.preventDefault=function(){T.Ja.preventDefault.call(this);var a=this.Z;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,dc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var hc="closure_listenable_"+(1E6*Math.random()|0),ic=0;var jc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ba=e;this.key=++ic;this.removed=this.wa=!1},kc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ba=null};var lc=function(a){this.src=a;this.o={};this.ka=0};lc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.o[f];a||(a=this.o[f]=[],this.ka++);var g=mc(a,b,d,e);-1<g?(b=a[g],c||(b.wa=!1)):(b=new jc(b,this.src,f,!!d,e),b.wa=c,a.push(b));return b};lc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var e=this.o[a];b=mc(e,b,c,d);return-1<b?(kc(e[b]),y(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.o[a],this.ka--),!0):!1};
lc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],e=0;e<d.length;e++)++b,kc(d[e]);delete this.o[c];this.ka--}return b};lc.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return wa(this.o,function(a){for(var f=0;f<a.length;++f)if(!(c&&a[f].type!=d||e&&a[f].capture!=b))return!0;return!1})};
var mc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ba==d)return e}return-1};var nc="closure_lm_"+(1E6*Math.random()|0),oc={},pc=0,rc=function(){var a=qc,b=Sb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},sc=function(a,b,c,d,e){if("array"==v(b))for(var f=0;f<b.length;f++)sc(a,b[f],c,d,e);else if(c=tc(c),a&&a[hc])a.Vb(b,c,pa(d)?!!d.capture:!!d,e);else{if(!b)throw Error("Invalid event type");f=pa(d)?!!d.capture:!!d;var g=uc(a);g||(a[nc]=g=new lc(a));c=g.add(b,c,!0,f,e);if(!c.proxy){e=rc();c.proxy=e;e.src=a;
e.listener=c;if(a.addEventListener)ec||(d=f),void 0===d&&(d=!1),a.addEventListener(b.toString(),e,d);else if(a.attachEvent)a.attachEvent(vc(b.toString()),e);else if(a.addListener&&a.removeListener)y("change"===b,"MediaQueryList only has a change event"),a.addListener(e);else throw Error("addEventListener and attachEvent are unavailable.");pc++}}},vc=function(a){return a in oc?oc[a]:oc[a]="on"+a},xc=function(a,b,c,d){var e=!0;if(a=uc(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=
b[a];f&&f.capture==c&&!f.removed&&(f=wc(f,d),e=e&&!1!==f)}return e},wc=function(a,b){var c=a.listener,d=a.Ba||a.src;if(a.wa&&"number"!=typeof a&&a&&!a.removed){var e=a.src;if(e&&e[hc])e.Wb(a);else{var f=a.type,g=a.proxy;e.removeEventListener?e.removeEventListener(f,g,a.capture):e.detachEvent?e.detachEvent(vc(f),g):e.addListener&&e.removeListener&&e.removeListener(g);pc--;if(f=uc(e)){g=a.type;var m;if(m=g in f.o){m=f.o[g];var C=Na(m,a),t;if(t=0<=C)y(null!=m.length),Array.prototype.splice.call(m,C,
1);m=t}m&&(kc(a),0==f.o[g].length&&(delete f.o[g],f.ka--));0==f.ka&&(f.src=null,e[nc]=null)}else kc(a)}}return c.call(d,b)},qc=function(a,b){if(a.removed)return!0;if(!Sb){if(!b)a:{b=["window","event"];for(var c=q,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new T(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.currentTarget;e;e=e.parentNode)d.push(e);
a=a.type;for(e=d.length-1;!b.Fa&&0<=e;e--){b.currentTarget=d[e];var f=xc(d[e],a,!0,b);c=c&&f}for(e=0;!b.Fa&&e<d.length;e++)b.currentTarget=d[e],f=xc(d[e],a,!1,b),c=c&&f}return c}return wc(a,new T(b,this))},uc=function(a){a=a[nc];return a instanceof lc?a:null},yc="__closure_events_fn_"+(1E9*Math.random()>>>0),tc=function(a){y(a,"Listener can not be null.");if(w(a))return a;y(a.handleEvent,"An object listener must have handleEvent method.");a[yc]||(a[yc]=function(b){return a.handleEvent(b)});return a[yc]};var zc={payload:"",type:"getClipboard"},Ac=function(){D.call(this)};k(Ac,D);Ac.prototype.onMessage=function(a,b,c){b=Fa(a,"any");switch(b.type){case "getClipboard":return Bc(c),!0;case "setClipboard":try{var d=Ga(a);Cc(d)}catch(e){U&&U.log(J,"Error handling SET_CLIPBOARD message",e)}break;default:U&&U.log(J,"Unknown message type: "+b.type,void 0)}return!1};Ac.prototype.Pa=function(){return["setClipboard","getClipboard"]};
var Bc=function(a){sc(window,"paste",function(b){(b=Dc(b))&&b.getData?(b=b.getData("text/plain"))?(M(U,"Got clipboard from OS, length: "+b.length),a(Ha({payload:b,type:"getClipboard"}))):a(Ha(zc)):M(U,"Got invalid clipboardData.")});document.execCommand("paste")},Cc=function(a){sc(window,"copy",function(b){var c=a.payload,d=Dc(b);d&&d.setData?(M(U,"Setting OS clipboard, length: "+c.length),d.setData("text/plain",c),b.preventDefault()):M(U,"Got invalid clipboardData.")});document.execCommand("copy")},
Dc=function(a){a=a.Z;return a.clipboardData?a.clipboardData:null},U=K("extension.ClipboardMessageHandler");z.add("url","downloads.init");z.add("status","downloads.getStatusResponse");z.add("totalBytes","downloads.getProgressResponse");z.add("bytesReceived","downloads.getProgressResponse");z.add("estimatedEndTime","downloads.getProgressResponse");z.add("danger","downloads.downloadResponse");var Ec=Ja("downloads.initResponse"),Fc=Ja("downloads.openResponse"),Gc=Ja("downloads.showResponse");var Hc=function(a,b){this.vb=100;this.ob=a;this.Lb=b;this.ra=0;this.m=null};Hc.prototype.get=function(){if(0<this.ra){this.ra--;var a=this.m;this.m=a.next;a.next=null}else a=this.ob();return a};Hc.prototype.put=function(a){this.Lb(a);this.ra<this.vb&&(this.ra++,a.next=this.m,this.m=a)};var Ic=function(a){q.setTimeout(function(){throw a;},0)},Jc,Kc=function(){var a=q.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!G("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;
a=sa(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!G("Trident")&&!G("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.Ma;c.Ma=null;a()}};return function(a){d.next={Ma:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?
function(a){var b=document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){q.setTimeout(a,0)}};var Lc=function(){this.va=this.W=null},Nc=new Hc(function(){return new Mc},function(a){a.reset()});Lc.prototype.add=function(a,b){var c=Nc.get();c.set(a,b);this.va?this.va.next=c:(y(!this.W),this.W=c);this.va=c};Lc.prototype.remove=function(){var a=null;this.W&&(a=this.W,this.W=this.W.next,this.W||(this.va=null),a.next=null);return a};var Mc=function(){this.next=this.scope=this.fn=null};Mc.prototype.set=function(a,b){this.fn=a;this.scope=b;this.next=null};
Mc.prototype.reset=function(){this.next=this.scope=this.fn=null};var Sc=function(a,b){Oc||Pc();Qc||(Oc(),Qc=!0);Rc.add(a,b)},Oc,Pc=function(){if(q.Promise&&q.Promise.resolve){var a=q.Promise.resolve(void 0);Oc=function(){a.then(Tc)}}else Oc=function(){var a=Tc;!w(q.setImmediate)||q.Window&&q.Window.prototype&&!G("Edge")&&q.Window.prototype.setImmediate==q.setImmediate?(Jc||(Jc=Kc()),Jc(a)):q.setImmediate(a)}},Qc=!1,Rc=new Lc,Tc=function(){for(var a;a=Rc.remove();){try{a.fn.call(a.scope)}catch(b){Ic(b)}Nc.put(a)}Qc=!1};var W=function(a){this.A=0;this.bb=void 0;this.X=this.I=this.C=null;this.oa=this.Aa=!1;if(a!=u)try{var b=this;a.call(void 0,function(a){V(b,2,a)},function(a){if(!(a instanceof Uc))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(d){}V(b,3,a)})}catch(c){V(this,3,c)}},Vc=function(){this.next=this.context=this.aa=this.U=this.O=null;this.ma=!1};Vc.prototype.reset=function(){this.context=this.aa=this.U=this.O=null;this.ma=!1};
var Wc=new Hc(function(){return new Vc},function(a){a.reset()}),Xc=function(a,b,c){var d=Wc.get();d.U=a;d.aa=b;d.context=c;return d},Yc=function(){var a=new W(u);V(a,2,"not-started");return a},Zc=function(a){return new W(function(b,c){c(a)})},ad=function(){var a,b,c=new W(function(c,e){a=c;b=e});return new $c(c,a,b)};
W.prototype.then=function(a,b,c){null!=a&&Da(a,"opt_onFulfilled should be a function.");null!=b&&Da(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return cd(this,w(a)?a:null,w(b)?b:null,c)};W.prototype.then=W.prototype.then;W.prototype.$goog_Thenable=!0;var X=function(a,b){return cd(a,null,b,void 0)};W.prototype.cancel=function(a){0==this.A&&Sc(function(){var b=new Uc(a);dd(this,b)},this)};
var dd=function(a,b){if(0==a.A)if(a.C){var c=a.C;if(c.I){for(var d=0,e=null,f=null,g=c.I;g&&(g.ma||(d++,g.O==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.A&&1==d?dd(c,b):(f?(d=f,y(c.I),y(null!=d),d.next==c.X&&(c.X=d),d.next=d.next.next):ed(c),fd(c,e,3,b)))}a.C=null}else V(a,3,b)},hd=function(a,b){a.I||2!=a.A&&3!=a.A||gd(a);y(null!=b.U);a.X?a.X.next=b:a.I=b;a.X=b},cd=function(a,b,c,d){var e=Xc(null,null,null);e.O=new W(function(a,g){e.U=b?function(c){try{var e=b.call(d,c);a(e)}catch(t){g(t)}}:a;
e.aa=c?function(b){try{var e=c.call(d,b);void 0===e&&b instanceof Uc?g(b):a(e)}catch(t){g(t)}}:g});e.O.C=a;hd(a,e);return e.O};W.prototype.Rb=function(a){y(1==this.A);this.A=0;V(this,2,a)};W.prototype.Sb=function(a){y(1==this.A);this.A=0;V(this,3,a)};
var V=function(a,b,c){if(0==a.A){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.A=1;a:{var d=c,e=a.Rb,f=a.Sb;if(d instanceof W){null!=e&&Da(e,"opt_onFulfilled should be a function.");null!=f&&Da(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");hd(d,Xc(e||u,f||null,a));var g=!0}else{if(d)try{var m=!!d.$goog_Thenable}catch(t){m=!1}else m=!1;if(m)d.then(e,f,a),g=!0;else{if(pa(d))try{var C=d.then;if(w(C)){id(d,C,e,f,a);
g=!0;break a}}catch(t){f.call(a,t);g=!0;break a}g=!1}}}g||(a.bb=c,a.A=b,a.C=null,gd(a),3!=b||c instanceof Uc||jd(a,c))}},id=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},m=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,m)}catch(C){m(C)}},gd=function(a){a.Aa||(a.Aa=!0,Sc(a.qb,a))},ed=function(a){var b=null;a.I&&(b=a.I,a.I=b.next,b.next=null);a.I||(a.X=null);null!=b&&y(null!=b.U);return b};W.prototype.qb=function(){for(var a;a=ed(this);)fd(this,a,this.A,this.bb);this.Aa=!1};
var fd=function(a,b,c,d){if(3==c&&b.aa&&!b.ma)for(;a&&a.oa;a=a.C)a.oa=!1;if(b.O)b.O.C=null,kd(b,c,d);else try{b.ma?b.U.call(b.context):kd(b,c,d)}catch(e){ld.call(null,e)}Wc.put(b)},kd=function(a,b,c){2==b?a.U.call(a.context,c):a.aa&&a.aa.call(a.context,c)},jd=function(a,b){a.oa=!0;Sc(function(){a.oa&&ld.call(null,b)})},ld=Ic,Uc=function(a){x.call(this,a)};va(Uc,x);Uc.prototype.name="cancel";var $c=function(a,b,c){this.Za=a;this.resolve=b;this.reject=c};var Y=function(a){D.call(this);this.Ka=a;this.L=ad();this.Ea=this.Cb.bind(this);this.l=null};k(Y,D);var od=function(a){var b=new Y(a);return X(md({url:a,orderBy:["-startTime"],limit:1}).then(function(a){if(0==a.length)return b;y(1==a.length,"A search query with limit=1 returns multiple items.");a=a[0];if(36E5>Date.now()-new Date(a.startTime))switch(nd(a)){case "downloaded":b.L.resolve();b.l=a.id;break;case "downloading":chrome.downloads.onChanged.addListener(b.Ea),b.l=a.id}return b}),function(){return b})};
Y.prototype.J=function(){chrome.downloads.onChanged.removeListener(this.Ea);D.prototype.J.call(this)};
var qd=function(a){return a.l?pd(a.l).then(function(a){return{type:"downloads.getProgressResponse",totalBytes:a.totalBytes,bytesReceived:a.bytesReceived,estimatedEndTime:a.estimatedEndTime?(new Date(a.estimatedEndTime)).getTime():void 0}}):Zc(new A("DownloadItem.getProgress()","UNEXPECTED_ERROR","No pending download in progress"))},rd=function(a){return a.l?X(pd(a.l).then(function(a){return nd(a)}),function(){return"interrupted"}):Yc()},nd=function(a){switch(a.state){case "complete":return a.exists?
"downloaded":"not-started";case "interrupted":return"interrupted";case "in_progress":return"downloading";default:return"not-started"}},pd=function(a){return null==a?Zc(new A("DownloadItem.getItemById","INVALID_ARGS","Missing required paramemter id")):md({id:a}).then(function(b){return 1!=b.length?Zc(new A("chrome.downloads.search","UNEXPECTED_ERROR","Multiple items returned for download id: "+a)):b[0]})},md=function(a){var b=ad();chrome.downloads.search(a,function(a){chrome.runtime.lastError?b.reject(Ia("chrome.downloads.search")):
b.resolve(a)});return b.Za};
Y.prototype.open=function(){var a=this;return this.l?pd(this.l).then(function(b){if("complete"!=b.state)throw new A("chrome.downloads.open","UNEXPECTED_ERROR","Cannot open "+b.filename+" before the download is completed.");if(!b.exists)throw new A("chrome.downloads.open","DOWNLOAD_ITEM_DELETED","filename: "+b.filename);"safe"!=b.danger&&sd&&sd.log(J,"Chrome marks file: "+b.filename+" as "+("danger:"+b.danger+", bravely continue."),void 0);chrome.downloads.open(a.l)}):Zc(new A("chrome.downloads.open","UNEXPECTED_ERROR",
"Missing downloadId"))};Y.prototype.show=function(){var a=this;return this.l?pd(this.l).then(function(b){if("complete"!=b.state)throw new A("chrome.downloads.show","UNEXPECTED_ERROR","Cannot open "+b.filename+" before the download is completed.");if(!b.exists)throw new A("chrome.downloads.show","DOWNLOAD_ITEM_DELETED","filename: "+b.filename);chrome.downloads.show(a.l)}):Zc(new A("chrome.downloads.show","UNEXPECTED_ERROR","Missing downloadId"))};
Y.prototype.download=function(){var a=this;return rd(this).then(function(b){if("not-started"==b||"interrupted"==b)a.L=ad(),chrome.downloads.onChanged.addListener(a.Ea),chrome.downloads.download({url:a.Ka},function(b){chrome.runtime.lastError&&a.L.reject(Ia("chrome.downloads.download"));a.l=b});return a.L.Za})};
Y.prototype.Cb=function(a){var b=this;if(a.id==this.l)if(a.state)switch(a.state.current){case "complete":this.L.resolve();break;case "interrupted":pd(a.id).then(function(a){b.L.reject(td(a.error,b.Ka))},function(a){a=B("DownloadItem.getItemById",a);sd&&sd.log(J,"Unexpected error finding download: "+a.message,void 0);b.L.reject(a)});break;case "in_progress":break;default:sd&&sd.log(J,"Unexpected downloadItem state: "+a.state.current,void 0),this.L.reject(new A("chrome.downloads.download","UNEXPECTED_ERROR",
"state: "+a.state.current))}else a.paused&&a.paused.current&&this.L.reject(new A("chrome.downloads.download","USER_CANCELED",this.Ka))};
function td(a,b){y(a,"Missing interrupt reason.");var c="CHROME_RUNTIME";switch(a){case "NETWORK_FAILED":c="NETWORK_FAILED";break;case "NETWORK_TIMEOUT":c="NETWORK_TIMEOUT";break;case "NETWORK_DISCONNECTED":c="NETWORK_DISCONNECTED";break;case "FILE_NO_SPACE":c="FILE_NO_SPACE";break;case "FILE_ACCESS_DENIED":c="FILE_ACCESS_DENIED";break;case "SERVER_UNREACHABLE":case "SERVER_BAD_CONTENT":c="SERVER_UNREACHABLE"}return new A("chrome.downloads.download",c,"url: "+b+" reason: "+a)}var sd=K("extension.DownloadItem");var vd=function(){this.Ya="";this.hb=ud};vd.prototype.toString=function(){return"SafeHtml{"+this.Ya+"}"};var ud={};var wd=function(){this.ua=void 0};wd.prototype.h=function(a){var b=[];xd(this,a,b);return b.join("")};
var xd=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==v(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],xd(a,a.ua?a.ua.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),yd(d,c),c.push(":"),xd(a,a.ua?a.ua.call(b,d,e):e,c),f=","));c.push("}");
return}}switch(typeof b){case "string":yd(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},zd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ad=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,yd=function(a,b){b.push('"',a.replace(Ad,function(a){var b=zd[a];
b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),zd[a]=b);return b}),'"')};var Cd=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,m,C,t,he,bd){if("%"==t)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("[goog.string.format] Not enough arguments");arguments[0]=e;return Bd[t].apply(null,arguments)})},Bd={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",
0)?a+E(" ",Number(c)-a.length):E(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+E(" ",a):f+E(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,m){return Bd.f(parseInt(a,
10),b,c,d,0,f,g,m)}};Bd.i=Bd.d;Bd.u=Bd.d;var Ed=function(){this.a=new Dd;this.Ca=new wd};Ed.prototype.format=function(a){a:if(null!=a){if(r(a)){if(/^[\s\xa0]*$/.test(a)){a=[];break a}a=JSON.parse(a)}var b=[];Fd(this,a,b,0);a=b}else a=[];var c="";for(b=0;b<a.length;b++){var d=a[b];d instanceof vd&&(d instanceof vd&&d.constructor===vd&&d.hb===ud?d=d.Ya:(Ba("expected object of type SafeHtml, got '"+d+"' of type "+v(d)),d="type_error:SafeHtml"));c+=d}return c};
var Fd=function(a,b,c,d){var e=v(b);switch(e){case "null":case "boolean":case "number":case "string":b=a.Ca.h(b);c.push(Gd(a.a,b,e));break;case "array":c.push(a.a.nb);for(e=0;e<b.length;e++)0<e&&c.push(a.a.$a),c.push(a.a.qa),c.push(E(a.a.ja,d+a.a.pa)),Fd(a,b[e],c,d+a.a.pa);0<e&&(c.push(a.a.qa),c.push(E(a.a.ja,d)));c.push(a.a.mb);break;case "object":c.push(a.a.zb);e=0;for(var f in b)b.hasOwnProperty(f)&&(0<e&&c.push(a.a.$a),c.push(a.a.qa),c.push(E(a.a.ja,d+a.a.pa)),c.push(Hd(a.a,a.Ca.h(f))),c.push(a.a.xb,
a.a.ja),Fd(a,b[f],c,d+a.a.pa),e++);0<e&&(c.push(a.a.qa),c.push(E(a.a.ja,d)));c.push(a.a.yb);break;default:b=a.Ca.h(""),c.push(Gd(a.a,b,"unknown"))}},Dd=function(){};h=Dd.prototype;h.ja=" ";h.qa="\n";h.zb="{";h.yb="}";h.nb="[";h.mb="]";h.$a=",";h.xb=":";h.Hb="";h.Fb="";var Hd=function(a,b){return a.Hb+b+a.Fb};Dd.prototype.Ib="";Dd.prototype.Gb="";var Gd=function(a,b,c){return Cd(a.Ib,c)+b+a.Gb};Dd.prototype.pa=2;var Id=function(){D.call(this);this.ha="chrome.downloads";this.Ha=new Set};k(Id,D);Id.prototype.Bb=function(a){this.Ha.delete(a)};Id.prototype.onConnect=function(a){this.Ha.add(new Jd(a,this.Bb.bind(this)))};Id.prototype.J=function(){this.Ha.forEach(function(a){a.close()});D.prototype.J.call(this)};
var Jd=function(a,b){var c=this;this.w=a;this.Ua=this.sa.bind(this);this.S=function(){Ma(c.K);c.w.onMessage.removeListener(c.Ua);c.w.onDisconnect.removeListener(c.S);b(c)};this.ga=new Ed;this.K=null;this.w.onMessage.addListener(this.Ua);this.w.onDisconnect.addListener(this.S)};Jd.prototype.close=function(){this.w.disconnect()};
Jd.prototype.sa=function(a){M(Kd,"Incoming message: "+this.ga.format(a));var b=Fa(a,"any"),c=this.Mb.bind(this,a.id);try{switch(b.type){case "hello":c({type:"helloResponse",version:chrome.runtime.getManifest().version});break;case "downloads.init":xa("downloads.init",a.type);var d=ya(a.url,"url");Ld(this,d,c);break;case "downloads.getStatus":Md(this,c);break;case "downloads.getProgress":Nd(this,c);break;case "downloads.download":Od(this,c);break;case "downloads.open":Pd(this,c);break;case "downloads.show":Qd(this,
c);break;default:c((new A("DownloadSession.onMessage","INVALID_ARGS","Unknown message type: "+b.type)).h())}}catch(e){c((new A("DownloadSession.onMessage","UNEXPECTED_ERROR",e.message)).h())}};
var Ld=function(a,b,c){X(od(b).then(function(b){a.K=b;c(Ec.h())}),function(a){c(B("DownloadItem.create",a).h())})},Md=function(a,b){Rd(a,b)&&X(rd(a.K).then(function(a){b({type:"downloads.getStatusResponse",status:a})}),function(a){b(B("DownloadItem.getStatus",a).h())})},Nd=function(a,b){Rd(a,b)&&X(qd(a.K).then(function(a){b(a)}),function(a){b(B("DownloadItem.getProgress",a).h())})},Od=function(a,b){X(a.K.download().then(function(){pd(a.K.l).then(function(a){b({type:"downloads.downloadResponse",danger:a.danger})})}),
function(a){b(B("DownloadItem.getDetails or DownloadItem.download",a).h())})},Pd=function(a,b){Rd(a,b)&&X(a.K.open().then(function(){b(Fc.h())}),function(a){b(B("DownloadItem.open",a).h())})},Qd=function(a,b){Rd(a,b)&&X(a.K.show().then(function(){b(Gc.h())}),function(a){b(B("DownloadItem.show",a).h())})};Jd.prototype.Mb=function(a,b){M(Kd,"Outgoing message: "+this.ga.format(b));b.id=a;this.w.postMessage(b)};
var Rd=function(a,b){return a.K?!0:(b((new A("checkInitialized","INVALID_ARGS","this.downloadItem_ == null")).h()),!1)},Kd=K("extension.NativeMessagingHandler");var Sd=function(a){D.call(this);this.ha=a;this.xa=new Set};k(Sd,D);Sd.prototype.Ab=function(a){this.xa.delete(a)};Sd.prototype.onConnect=function(a){this.xa.add(new Td(a,this.Ab.bind(this)))};Sd.prototype.J=function(){this.xa.forEach(function(a){a.close()});D.prototype.J.call(this)};
var Td=function(a,b){var c=this;this.ba=a;this.$=chrome.runtime.connectNative(a.name);this.Xa=this.Eb.bind(this);this.Wa=this.Db.bind(this);this.S=function(){c.close();b(c)};this.ga=new Ed;this.ba.onMessage.addListener(this.Xa);this.ba.onDisconnect.addListener(this.S);this.$.onMessage.addListener(this.Wa);this.$.onDisconnect.addListener(this.S)};
Td.prototype.close=function(){this.ba.onMessage.removeListener(this.Xa);this.ba.onDisconnect.removeListener(this.S);this.$.onMessage.removeListener(this.Wa);this.$.onDisconnect.removeListener(this.S);this.ba.disconnect();this.$.disconnect()};Td.prototype.Db=function(a){M(Ud,"Native => Webapp: "+this.ga.format(a));this.ba.postMessage(a)};Td.prototype.Eb=function(a){M(Ud,"Webapp => Native: "+this.ga.format(a));this.$.postMessage(a)};var Ud=K("extension.NativeMessagingHandler");var Vd=function(a){D.apply(this,arguments)};k(Vd,D);Vd.prototype.onMessage=function(a,b,c){a=Fa(a,"any");try{switch(a.type){case "tabs.highlight":return Wd(b,c);default:return Xd(c,new A("TabsMessageHandler.onMessage","INVALID_ARGS","Unknown message type: "+a.type))}}catch(d){return Xd(c,new A("TabsMessageHandler.onMessage","UNEXPECTED_ERROR","Unexpected error: "+d.message))}};Vd.prototype.Pa=function(){return["tabs.highlight"]};
var Wd=function(a,b){if(a.tab){var c=a.tab.windowId,d=a.tab.index;chrome.windows.update(c,{focused:!0},function(){chrome.tabs.highlight({windowId:c,tabs:d},function(){b(Ka.h())})});return!0}b(Ka.h());return!1};function Xd(a,b){Yd&&Yd.log(J,"Sending error: "+b.message,b);a(b.h());return!1}var Yd=K("extension.TabsMessageHandler");var Zd=function(){this.ab=ua()},$d=null;Zd.prototype.set=function(a){this.ab=a};Zd.prototype.reset=function(){this.set(ua())};Zd.prototype.get=function(){return this.ab};var ae=function(a){this.Jb=a||"";$d||($d=new Zd);this.Qb=$d};h=ae.prototype;h.La=!0;h.eb=!0;h.Ob=!0;h.Nb=!0;h.fb=!1;h.Pb=!1;var Z=function(a){return 10>a?"0"+a:String(a)},be=function(a,b){a=(a.gb-b)/1E3;b=a.toFixed(3);var c=0;if(1>a)c=2;else for(;100>a;)c++,a*=10;for(;0<c--;)b=" "+b;return b},ce=function(a){ae.call(this,a)};va(ce,ae);var de=function(){this.Kb=sa(this.kb,this);this.na=new ce;this.na.eb=!1;this.na.fb=!1;this.Qa=this.na.La=!1;this.rb={}},ee=function(){var a=new de;if(1!=a.Qa){tb();var b=sb;var c=a.Kb;b.ea||(b.ea=[]);b.ea.push(c);a.Qa=!0}};
de.prototype.kb=function(a){if(!this.rb[a.Ra]){var b=this.na;var c=[];c.push(b.Jb," ");if(b.eb){var d=new Date(a.gb);c.push("[",Z(d.getFullYear()-2E3)+Z(d.getMonth()+1)+Z(d.getDate())+" "+Z(d.getHours())+":"+Z(d.getMinutes())+":"+Z(d.getSeconds())+"."+Z(Math.floor(d.getMilliseconds()/10)),"] ")}b.Ob&&c.push("[",be(a,b.Qb.get()),"s] ");b.Nb&&c.push("[",a.Ra,"] ");b.Pb&&c.push("[",a.R.name,"] ");c.push(a.getMessage());b.fb&&(d=a.za)&&c.push("\n",d instanceof Error?d.message:d.toString());b.La&&c.push("\n");
b=c.join("");if(c=fe)switch(a.R){case mb:ge(c,"info",b);break;case J:ge(c,"error",b);break;case nb:ge(c,"warn",b);break;default:ge(c,"log",b)}}};var fe=q.console,ge=function(a,b,c){if(a[b])a[b](c);else a.log(c)};(function(){ee();chrome.browserAction.onClicked.addListener(function(){return chrome.tabs.create({url:"https://remotedesktop.google.com/"})});var a=new Ob(chrome.runtime.onMessageExternal,chrome.runtime.onConnectExternal);Qb(a,new Ac);Qb(a,new Vd);Pb(a,new Sd("com.google.chrome.remote_assistance"));Pb(a,new Sd("com.google.chrome.remote_desktop"));Pb(a,new Id);a.start()})();
